export const places = [
  {
    name: 'Hong Kong',
    location: [22.3193, 114.1694],
    id: 'hongKong',
    color: 'accent-1',
  },
  {
    name: 'Paris',
    location: [48.8566, 2.3522],
    id: 'paris',
    color: 'accent-1',
  },
  {
    name: 'Sydney',
    location: [-33.8830555556, 151.216666667],
    id: 'sydney',
    color: 'accent-1',
  },
  {
    name: 'Auckland',
    location: [-36.8485, 174.7633],
    id: 'auckland',
    color: 'accent-1',
  },
  {
    name: 'Fiji',
    location: [-17.7134, 178.065],
    id: 'fiji',
    color: 'accent-1',
  },
  {
    name: 'Tel-Aviv',
    location: [32.0853, 34.7818],
    id: 'tlv',
    color: 'accent-1',
  },
  {
    name: 'Hawaii',
    location: [21.3, -157.5828],
    id: 'hawaii',
    color: 'accent-2',
  },
  {
    name: 'NYC',
    location: [40.7128, -74.006],
    id: 'nyc',
    color: 'accent-2',
  },
  {
    name: 'Salt Lake City',
    location: [40.7608, -111.891],
    id: 'saltLakeCity',
    color: 'accent-2',
  },
  {
    name: 'Lala land',
    location: [34.0522, -118.2437],
    id: 'la',
    color: 'accent-2',
  },
  {
    name: 'Buenos Aires',
    location: [-34.6037, -58.3816],
    id: 'buenos',
    color: 'accent-4',
  },
  {
    name: 'Moscow',
    location: [55.7558, 37.6173],
    id: 'moscow',
    color: 'accent-4',
  },
  {
    name: 'Beijing',
    location: [39.9042, 116.4074],
    id: 'beijing',
    color: 'accent-4',
  },
  {
    name: 'Toronto',
    location: [43.6532, -79.3832],
    id: 'toronto',
    color: 'brand',
  },
  {
    name: 'vancouver',
    location: [49.2827, -123.1207],
    id: 'vancouver',
    color: 'brand',
  },
  {
    name: 'Greenland',
    location: [71.7069, -42.6043],
    id: 'greenland',
    color: 'brand',
  },
];

export const connections = [
  // Honeymoon connections
  {
    fromTarget: 'tlv',
    toTarget: 'paris',
    thickness: 'xxsmall',
    color: 'accent-1',
    type: 'direct',
  },
  {
    fromTarget: 'paris',
    toTarget: 'sydney',
    thickness: 'xxsmall',
    color: 'accent-1',
    type: 'direct',
  },
  {
    fromTarget: 'sydney',
    toTarget: 'auckland',
    thickness: 'xxsmall',
    color: 'accent-1',
    type: 'direct',
  },
  {
    fromTarget: 'auckland',
    toTarget: 'fiji',
    thickness: 'xxsmall',
    color: 'accent-1',
    type: 'direct',
  },
  {
    fromTarget: 'fiji',
    toTarget: 'hongKong',
    thickness: 'xxsmall',
    color: 'accent-1',
    type: 'direct',
  },
  {
    fromTarget: 'hongKong',
    toTarget: 'tlv',
    thickness: 'xxsmall',
    color: 'accent-1',
    type: 'direct',
  },
  // 23
  {
    fromTarget: 'tlv',
    toTarget: 'nyc',
    thickness: 'xxsmall',
    color: 'accent-2',
    type: 'direct',
  },
  {
    fromTarget: 'nyc',
    toTarget: 'saltLakeCity',
    thickness: 'xxsmall',
    color: 'accent-2',
    type: 'direct',
  },
  {
    fromTarget: 'saltLakeCity',
    toTarget: 'hawaii',
    thickness: 'xxsmall',
    color: 'accent-2',
    type: 'direct',
  },
  {
    fromTarget: 'hawaii',
    toTarget: 'la',
    thickness: 'xxsmall',
    color: 'accent-2',
    type: 'direct',
  },
  {
    fromTarget: 'la',
    toTarget: 'tlv',
    thickness: 'xxsmall',
    color: 'accent-2',
    type: 'direct',
  },
  // goto
  {
    fromTarget: 'buenos',
    toTarget: 'moscow',
    thickness: 'xxsmall',
    color: 'accent-4',
    type: 'direct',
  },
  {
    fromTarget: 'moscow',
    toTarget: 'beijing',
    thickness: 'xxsmall',
    color: 'accent-4',
    type: 'direct',
  },
  {
    fromTarget: 'beijing',
    toTarget: 'buenos',
    thickness: 'xxsmall',
    color: 'accent-4',
    type: 'direct',
  },
  // brand
  {
    fromTarget: 'toronto',
    toTarget: 'vancouver',
    thickness: 'xxsmall',
    color: 'brand',
    type: 'direct',
  },
  {
    fromTarget: 'vancouver',
    toTarget: 'greenland',
    thickness: 'xxsmall',
    color: 'brand',
    type: 'direct',
  },
  {
    fromTarget: 'greenland',
    toTarget: 'toronto',
    thickness: 'xxsmall',
    color: 'brand',
    type: 'direct',
  },
];
